version: '3.8'

services:

  options_web:
    container_name: 'aspnet-options-app'
    image: 'aspnet-options-app'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "5002:80"
     - "7003:443"
    networks:
      - aspnet-options-network
      - aspnet-hotel-network
      - admin-ms-network
    restart: always
    depends_on:
      - options_pg
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Host=options_pg;Server=options_pg;Port=5432;Database=OptionsDbDriver; IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=7003
      - ASPNETCORE_Kestrel__Certificates__Default__Password=toto123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - .aspnet/https:/https/
  options_pg:
    image: postgres:latest
    container_name: options_pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=OptionsDbDriver
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - options_app_data:/var/lib/postgresql/data
    networks:
      - aspnet-options-network
networks:
  aspnet-hotel-network:
    name: aspnet-hotel-network
    external: true
  admin-ms-network:
    name: admin-ms-network
    external: true
  aspnet-options-network:
    name: aspnet-options-network
volumes:
  options_app_data: